In [2]:
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as ex
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

## Data preparation: Apply data cleaning and wrangling for PCA

In [3]:
df = pd.read_csv("2021data.csv")
df.shape

(1170, 162)

In [4]:
missing = df.isnull().sum()
missing

Model Year                                                           0
Mfr Name                                                             0
Division                                                             0
Carline                                                              0
Verify Mfr Cd                                                        0
                                                                  ...
120V Charge time at 120 Volts (hours)                             1170
PHEV Total Driving Range (rounded to nearest 10 miles)DISTANCE    1170
City PHEV Composite MPGe                                          1170
Hwy PHEV Composite MPGe                                           1170
Comb PHEV Composite MPGe                                          1170
Length: 162, dtype: int64

We are missing significantly large amount of data. <br>
Therefore, we seek to deprecate columns with over 20% missing data

In [5]:
col_to_drop = df.columns[missing > len(df) * 0.2]
col_to_drop

Index(['Guzzler? ', 'Air Aspir Method', 'Trans, Other', 'Max Biodiesel %',
       'Range1 - Model Type Driving Range - Conventional Fuel', '2Dr Pass Vol',
       '2Dr Lugg Vol', '4Dr Pass Vol', '4Dr Lugg Vol', 'Htchbk Pass Vol',
       'Htchbk Lugg Vol', 'City2 FE (Guide) - Alternative Fuel',
       'Hwy2 Fuel FE (Guide) - Alternative Fuel',
       'Comb2 Fuel FE (Guide) - Alternative Fuel',
       'City2 Unadj FE - Alternative Fuel', 'Hwy2 Unadj FE - Alternative Fuel',
       'Comb2 Unadj FE - Alternative Fuel',
       'City2 Unrd Adj FE - Alternative Fuel',
       'Hwy2 Unrd Adj FE - Alternative Fuel',
       'Cmb2 Unrd Adj FE - Alternative Fuel',
       ' Range2 - Alt Fuel Model Typ Driving Range - Alternative Fuel',
       ' Fuel2 Usage - Alternative Fuel',
       ' Fuel2 Usage Desc - Alternative Fuel', 'Fuel2 Unit - Alternative Fuel',
       'Fuel2 Unit Desc - Alternative Fuel',
       'Fuel2 Annual Fuel Cost - Alternative Fuel',
       'City CO2 Rounded Adjusted - Fuel2', 'Hwy CO2 Rounded Adjusted - Fuel2',
       'Comb CO2 Rounded Adjusted - Fuel2',
       'Fuel2 EPA Calculated Annual Fuel Cost - Alternative Fuel',
       'Car/Truck Category - Cash for Clunkers Bill.', 'Unnamed: 74',
       'Relabel', 'Relabel Desc', 'Comments - Mfr Eng Cnfg', 'Cyl Deact Desc',
       'Var Valve Lift Desc', 'Energy Storage Device Desc',
       'Energy Storage Device,If Other', '# Batteries', 'Battery Type Desc',
       'Battery Type, If Other', 'Total Voltage for Battery Pack(s)',
       'Batt Energy Capacity (Amp-hrs)', 'Batt Specific Energy (Watt-hr/kg)',
       'Batt Charger Type Desc', 'Comments', '# Capacitors',
       'Regen Braking Type Desc', 'Regen Braking Type, If Other',
       'Regen Braking Wheels Source (Front, Rear, Both)',
       'Driver Cntrl Regen Braking?', 'Fuel Cell Desc',
       'Usable H2 Fill Capacity (kg)', 'Fuel Cell Onboard H2 Capacity (kg)',
       'HEV-EV Comments', '# Drive Motor Gen', 'Motor Gen Type Desc',
       'Motor Gen Type, If Other', 'Rated Motor Gen Power (kW)',
       'Fuel Metering Type 1 Desc', 'Fuel Metering Type 2 Desc',
       'Fuel Cell Vehicle (Y or N)', 'Off Board Charge Capable (Y or N)',
       'Model Type Desc (MFR entered)',
       'Charge Depleting Calc Appr Code (PHEV only)',
       'Charge Depleting Calc Appr Desc (PHEV only)',
       'Charge Sustaining Calc Appr Code (PHEV only)',
       'Charge Sustaining Calc Appr Desc (PHEV only)',
       'EPA Calculated Annual Fuel Cost', 'EPA Calculated Gas Guzzler MPG',
       'MFR Calculated Gas Guzzler MPG ',
       'EPA Calculated Gas Guzzler Indicator (Y or N)', 'Unnamed: 130',
       'GHG 1-10 rating on Ethanol (EPA Determined)',
       '#1 EPA Smog Rating (EPA Smog 1-10 Rating on Label for Test Group 1)',
       'SmartWay1 (EPA-derived SmartWay rating for Test Group 1)',
       '#2 Smog Rating Test Group',
       '#2 Mfr Smog Rating (Mfr Smog 1-10 Rating on Label for Test Group 2)',
       '#2 EPA Smog Rating (EPA Smog 1-10 Rating on Label for Test Group 2)',
       'SmartWay2 (EPA-derived SmartWay rating for Test Group 2)',
       '#3 Smog Rating Test Group',
       '#3 Mfr Smog Rating (Mfr Smog 1-10 Rating on Label for Test Group 3)',
       '#3 EPA Smog Rating (EPA Smog 1-10 Rating on Label for Test Group 3)',
       'SmartWay3 (EPA-derived SmartWay rating for Test Group 3)',
       '#4 Smog Rating Test Group',
       '#4 Mfr Smog Rating (Mfr Smog 1-10 Rating on Label for Test Group 4)',
       '#4 EPA Smog Rating (EPA Smog 1-10 Rating on Label for Test Group 4)',
       'SmartWay4 (EPA-derived SmartWay rating for Test Group 4)',
       '$ You Save over 5 years (amount saved in fuel costs over 5 years - on label) ',
       'CO2-PHEV Composite Rounded Adjusted Combined CO2',
       '240V Charge Time at 240 volts (hours)',
       '120V Charge time at 120 Volts (hours)',
       'PHEV Total Driving Range (rounded to nearest 10 miles)DISTANCE',
       'City PHEV Composite MPGe', 'Hwy PHEV Composite MPGe',
       'Comb PHEV Composite MPGe'],
      dtype='object')

In [6]:
df.drop(columns = col_to_drop,inplace = True)
df.shape

(1170, 65)

In [8]:
df.to_csv("2021data2.csv",index= False)

In [9]:
df = pd.read_csv('2021data2.csv')

In [10]:
numerical_col = []
categorical_col = []

for i in df.columns:
    if df[i].dtype == np.dtype('float64') or df[i].dtype == np.dtype('int64'):
        numerical_col.append(df[i])
    else:
        categorical_col.append(df[i])

In [11]:
numerical_df = pd.concat(numerical_col,axis = 1)
numerical_df.shape

(1170, 28)

In [12]:
categorical_df = pd.concat(categorical_col,axis=1)
categorical_df.shape

(1170, 37)

In [13]:
numerical_df.head()

,Model Year,Index (Model Type Index),Eng Displ,# Cyl,City FE (Guide) - Conventional Fuel,Hwy FE (Guide) - Conventional Fuel,Comb FE (Guide) - Conventional Fuel,City Unadj FE - Conventional Fuel,Hwy Unadj FE - Conventional Fuel,Comb Unadj FE - Conventional Fuel,...,Exhaust Valves Per Cyl,Carline Class,EPA FE Label Dataset ID,FE Rating (1-10 rating on Label),GHG Rating (1-10 rating on Label),#1 Mfr Smog Rating (Mfr Smog 1-10 Rating on Label for Test Group 1),$ You Spend over 5 years (increased amount spent in fuel costs over 5 years - on label),City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Rounded Adjusted (as shown on FE Label)
0,2021,39,3.5,6,21,22,21,28.7000,30.2000,29.3561,...,2,1,28601,4,4,3,4000.0,420,406,420
1,2021,5,4.0,8,14,21,17,17.3588,29.2584,21.2475,...,2,1,28309,3,3,3,6750.0,636,426,541
2,2021,4,4.0,8,18,24,20,22.5379,34.2945,26.6489,...,2,1,28080,4,4,3,4750.0,494,364,435
3,2021,5,5.2,10,13,20,16,15.8765,26.0378,19.2586,...,2,1,27210,2,2,1,7750.0,663,450,567
4,2021,7,5.2,10,14,23,17,15.8768,29.6317,20.0690,...,2,1,28418,3,3,1,6750.0,645,386,528

## Replace null values in numerical data with mean values

In [14]:
numerical_df = numerical_df.apply(lambda x: x.fillna(np.mean(x)))
numerical_df.isnull().sum()

Model Year                                                                                                   0
Index (Model Type Index)                                                                                     0
Eng Displ                                                                                                    0
# Cyl                                                                                                        0
City FE (Guide) - Conventional Fuel                                                                          0
Hwy FE (Guide) - Conventional Fuel                                                                           0
Comb FE (Guide) - Conventional Fuel                                                                          0
City Unadj FE - Conventional Fuel                                                                            0
Hwy Unadj FE - Conventional Fuel                                                                             0
Comb Unadj FE - Conventional Fuel                                                                            0
City Unrd Adj FE - Conventional Fuel                                                                         0
Hwy Unrd Adj FE - Conventional Fuel                                                                          0
Comb Unrd Adj FE - Conventional Fuel                                                                         0
# Gears                                                                                                      0
Max Ethanol % - Gasoline                                                                                     0
Annual Fuel1 Cost - Conventional Fuel                                                                        0
EPA Calculated Annual Fuel Cost - Conventional Fuel -----  Annual fuel cost error. Please revise Verify.     0
Intake Valves Per Cyl                                                                                        0
Exhaust Valves Per Cyl                                                                                       0
Carline Class                                                                                                0
EPA FE Label Dataset ID                                                                                      0
FE Rating (1-10 rating on Label)                                                                             0
GHG Rating (1-10 rating on Label)                                                                            0
#1 Mfr Smog Rating (Mfr Smog 1-10 Rating on Label for Test Group 1)                                          0
$ You Spend over 5 years (increased amount spent in fuel costs over 5 years - on label)                      0
City CO2 Rounded Adjusted                                                                                    0
Hwy CO2 Rounded Adjusted                                                                                     0
Comb CO2 Rounded Adjusted (as shown on FE Label)                                                             0
dtype: int64

In [15]:
scaler = StandardScaler()

In [16]:
scaled_values = scaler.fit_transform(numerical_df)
scaled_values

array([[ 0.        , -0.83430615,  0.22513586, ..., -0.37508489,
         0.71687874,  0.0589996 ],
       [ 0.        , -0.95661525,  0.59017044, ...,  1.35921179,
         0.96681114,  1.23277326],
       [ 0.        , -0.96021258,  0.59017044, ...,  0.2190723 ,
         0.19202071,  0.20450873],
       ...,
       [ 0.        , -0.97100456,  0.29814277, ...,  0.64461732,
         0.7543686 ,  0.68953917],
       [ 0.        , -0.7875409 , -0.86996788, ..., -0.08603544,
        -0.3828238 , -0.19321623],
       [ 0.        , -0.78394357, -0.86996788, ..., -0.27070592,
        -0.43281028, -0.32902475]])

In [17]:
pca = PCA()
pca_values = pca.fit_transform(scaled_values)
pca_values = pd.DataFrame(pca_values)
pca_values.head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,-1.181462,-0.634556,0.989107,0.289855,1.036108,-0.131205,-0.434936,0.424139,-0.531828,0.312403,...,0.052593,-0.070314,-0.017836,0.015745,-0.037457,0.013481,-0.010174,0.000000e+00,0.000000e+00,1.098972e-14
1,-4.235060,-0.685117,2.339207,-0.133076,0.402219,-0.168385,0.354205,-0.110575,-0.269627,-0.018770,...,-0.037775,0.024898,-0.021926,-0.001615,-0.008545,0.012985,-0.001914,-4.193982e-16,-1.951071e-16,2.142214e-17
2,-1.760177,-0.443107,1.815350,0.034132,0.365941,-0.715231,-0.513725,0.139377,-0.124924,-0.479656,...,0.020011,-0.019174,0.046384,-0.049570,-0.004245,-0.004601,0.000513,-3.665409e-16,2.524576e-16,-7.605944e-17
3,-5.712779,-0.481687,3.407211,0.037402,-1.238486,-0.734825,-0.350882,0.368382,0.579167,-0.376677,...,-0.058763,0.020623,-0.043111,0.025069,0.030931,0.004020,0.001286,-4.535215e-16,3.911866e-16,-8.822868e-18
4,-4.584877,-0.226289,3.004320,0.540593,0.426075,-0.355015,-0.313804,0.799690,0.066798,-1.102542,...,0.023240,-0.037639,-0.012789,0.018443,-0.004131,0.019981,-0.006732,4.883589e-16,1.969987e-16,3.969380e-17

In [18]:
new_col = ['PCA_' + str(i) for i in range(1,len(pca_values.columns) + 1)]
old_col = list(pca_values.columns)
col_mapper = dict(zip(old_col,new_col))

pca_values.rename(columns=col_mapper, inplace = True)

In [19]:
pca_values.head()

,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,PCA_10,...,PCA_19,PCA_20,PCA_21,PCA_22,PCA_23,PCA_24,PCA_25,PCA_26,PCA_27,PCA_28
0,-1.181462,-0.634556,0.989107,0.289855,1.036108,-0.131205,-0.434936,0.424139,-0.531828,0.312403,...,0.052593,-0.070314,-0.017836,0.015745,-0.037457,0.013481,-0.010174,0.000000e+00,0.000000e+00,1.098972e-14
1,-4.235060,-0.685117,2.339207,-0.133076,0.402219,-0.168385,0.354205,-0.110575,-0.269627,-0.018770,...,-0.037775,0.024898,-0.021926,-0.001615,-0.008545,0.012985,-0.001914,-4.193982e-16,-1.951071e-16,2.142214e-17
2,-1.760177,-0.443107,1.815350,0.034132,0.365941,-0.715231,-0.513725,0.139377,-0.124924,-0.479656,...,0.020011,-0.019174,0.046384,-0.049570,-0.004245,-0.004601,0.000513,-3.665409e-16,2.524576e-16,-7.605944e-17
3,-5.712779,-0.481687,3.407211,0.037402,-1.238486,-0.734825,-0.350882,0.368382,0.579167,-0.376677,...,-0.058763,0.020623,-0.043111,0.025069,0.030931,0.004020,0.001286,-4.535215e-16,3.911866e-16,-8.822868e-18
4,-4.584877,-0.226289,3.004320,0.540593,0.426075,-0.355015,-0.313804,0.799690,0.066798,-1.102542,...,0.023240,-0.037639,-0.012789,0.018443,-0.004131,0.019981,-0.006732,4.883589e-16,1.969987e-16,3.969380e-17

In [20]:
output = pd.concat([df, pca_values],axis = 1)